version: "2"
linters:
  enable:
    - asciicheck
    - bidichk
    - revive
  settings:
    errcheck:
      exclude-functions:
        - (*github.com/godbus/dbus/v5.Conn).Close
        - (net.Conn).Close
        - (net.Listener).Close
        - (*os.File).Close
        - golang.org/x/sys/unix.Close
    revive:
      rules:
        - name: var-naming
          arguments:
            - - ID
              - UID
            - []
            - - upperCaseConst: false
formatters:
  enable:
    - gofmt
    - goimports
