name: Go

on: [ push, pull_request ]

jobs:
  build:
    name: Build
    strategy:
      matrix:
        os: [ ubuntu-22.04, ubuntu-24.04 ]
        go_version: [ '1.18', '^1.18' ]
    runs-on: ${{ matrix.os }}
    steps:
      - name: Allow unprivileged user namespaces
        # needed on Ubuntu >= 24.04
        run: sudo sysctl -e -w kernel.apparmor_restrict_unprivileged_userns=0

      - name: Check out code
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: ${{ matrix.go_version }}

      - name: Install package dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y libseccomp-dev

      - name: Build
        run: go build -v ./...

      - name: Test
        run: go test -v ./...
